[package]
name = "ftl"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
# Logging
pretty_env_logger = "0.4.0"
log = "0.4"
# Parallelism
rayon = "1.5"
flume = "0.10.14"
# File crawling
memmap2 = "0.5.7"
seahash = "4.1.0"
walkdir = "2"
# Database
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_rusqlite = "0.31.0"
r2d2_sqlite = "0.21.0"
r2d2 = "0.8.10"
# Other
regex = "1.6.0"
lazy_static = "1.4.0"
toml = "0.5.0"
chrono = "0.4"