[package]
name = "ftl"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
description = "An almost-static site generator."

[dependencies]
# Logging / Errors
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-error = "0.2.0"
tracing = "0.1.37"
color-eyre = "0.6.2"
# Parallelism
rayon = "1.5"
flume = "0.10.14"
# File crawling
seahash = "4.1"
walkdir = "2"
# Database
rusqlite = { version = "0.28", features = ["bundled"] }
r2d2_sqlite = "0.21"
r2d2 = "0.8.10"
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
serde_rusqlite = "0.31"
# Rendering/Parsing
regex = "1.6"
toml = "0.5"
tera = "1"
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
grass = "0.11"
lol_html = "0.3.1"
# Other
lazy_static = "1.4"
num_enum = "0.5"
time = { version = "0.3", features = ["serde", "parsing", "formatting"] }
clap = { version = "4", features = ["derive"] }
once_cell = "1.15.0"
console = "0.15.2"
dialoguer = "0.10.2"
indicatif = "0.17.1"
nom = "7.1.1"

