root_url = "foo"

[build]
compile_sass = true
external_links_new_tab = false
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false
highlight_code = true
render_emoji = true

[serve]
address = ""
port = 0
cache_max_size = 0
cache_ttl = 0
cache_tti = 0

[extra]
