root_url = "https://ftl.rs"

[build]
compile_sass = true
external_links_new_tab = false
external_links_no_follow = false
external_links_no_referrer = false

[render]
smart_punctuation = true
highlight_code = true
render_emoji = true
minify_html = false
minify_css = false

[serve]
address = "127.0.0.1"
port = 8080

[extra]
title = ""
description = ""
language = "en-US"
