root_url = "https://ftl.rs"
title = ""
description = ""
language = "en-US"

[build]
compile_sass = true
inline_extensions = ["rs"]
external_links_new_tab = false
external_links_no_follow = false
external_links_no_referrer = false

[render]
smart_punctuation = false
highlight_code = false
highlight_theme = "Halflife"
render_emoji = false
minify_html = false
minify_css = false

[serve]
address = "127.0.0.1"
port = 8080

[extra]
