root_url = "https://ftl.rs"

[build]
compile_sass = true
external_links_new_tab = false
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = true
highlight_code = true
render_emoji = true

[serve]
address = "0.0.0.0"
port = 8080
error_template = "error.html"
# Whether or not to "preheat" the cache.
# If true, FTL will query all known routes and insert them into the cache
# before starting the web server.
# 
# If this causes the maximum cache size to be exceeded, some routes will
# be evicted. Which routes are evicted is non-deterministic.
cache_preheat = true
# Maximum cache size in MB
cache_max_size = 512
# TTL/TTI in seconds
cache_ttl = 1800
cache_tti = 500

[extra]
title = ""
description = ""
language = "en-US"
